export const collections = {
  catalogProducts: "inv-products",
  catalogProductsCategory: "inv-products-category",
  catalogProviders: "inv-providers",
  catalogServices: "inv-services",
  catalogServicesCategory: "inv-services-category",
  bankingTransactions: "prod-banking-transaction",
  bankReconciliation: "prod-bank-reconciliation",
  clients: "prodseller-clients",
  qualityAssurance: "statistics-qa-poll",
  dailyClosing: "prod-daily-closing",
  expenses: "prod-cash-outflows",
  sales: "prod-sales",
  salesDetails: "prod-sales-details",
  tmpRaffle: "tmp-raffle",
  deletedBankTx: "removed-from-banking-transaction",
  deletedExpense: "removed-from-cash-outflows",
  deletedSales: "removed-from-sales",
  deletedSalesDetails: "removed-from-sales-details"
}