export const servicesEneglimar = [
  { code: "SERVCJA04", category: "CEJAS", description: "[%60] Pigmentación de cejas", baseValue: 7.00, finalValue: 7.84, taxIVA: 0.84, taxDebit: 0.18, taxCredit: 0.35, sellerCommission: 60, type: "S", retentionIVA: true, active: true, promo: { discountDay: 0, cash: 12 } },
  { code: "SERVCJA10", category: "CEJAS", description: "[%60] Depilación con cera + pigmentación", baseValue: 10.00, finalValue: 11.20, taxIVA: 1.20, taxDebit: 0.25, taxCredit: 0.50, sellerCommission: 60, type: "S", retentionIVA: true, active: true, promo: { discountDay: 0, cash: 12 } },
  { code: "SERVUNA01", category: "UNIAS", description: "[%60] Manicure rusa hombre", baseValue: 5.00, finalValue: 5.60, taxIVA: 0.60, taxDebit: 0.13, taxCredit: 0.25, sellerCommission: 60, type: "S", retentionIVA: true, active: true, promo: { discountDay: 0, cash: 12 } },
  { code: "SERVUNA03", category: "UNIAS", description: "[%60] Manicure rusa + esmaltado tradicional mujer", baseValue: 7.00, finalValue: 7.84, taxIVA: 0.84, taxDebit: 0.18, taxCredit: 0.35, sellerCommission: 60, type: "S", retentionIVA: true, active: true, promo: { discountDay: 0, cash: 12 } },
  { code: "SERVUNA06", category: "UNIAS", description: "[%60] Manicure rusa + esmaltado semipermanente", baseValue: 12.00, finalValue: 13.44, taxIVA: 1.44, taxDebit: 0.30, taxCredit: 0.60, sellerCommission: 60, type: "S", retentionIVA: true, active: true, promo: { discountDay: 0, cash: 12 } },
  { code: "SERVUNA09", category: "UNIAS", description: "[%60] Baño de acrílicas en uñas naturales", baseValue: 15.00, finalValue: 16.80, taxIVA: 1.80, taxDebit: 0.38, taxCredit: 0.75, sellerCommission: 60, type: "S", retentionIVA: true, active: true, promo: { discountDay: 0, cash: 12 } },
  { code: "SERVUNA12", category: "UNIAS", description: "[%60] Acrílicas (diseños básicos)", baseValue: 20.00, finalValue: 22.40, taxIVA: 2.40, taxDebit: 0.50, taxCredit: 1.00, sellerCommission: 60, type: "S", retentionIVA: true, active: true, promo: { discountDay: 0, cash: 12 } },
  { code: "SERVUNA15", category: "UNIAS", description: "[%60] Acrílicas (diseños elaborados)", baseValue: 25.00, finalValue: 28.00, taxIVA: 3.00, taxDebit: 0.63, taxCredit: 1.25, sellerCommission: 60, type: "S", retentionIVA: true, active: true, promo: { discountDay: 0, cash: 12 } },
  { code: "SERVUNA18", category: "UNIAS", description: "[%60] Retoques de acrílicas", baseValue: 12.00, finalValue: 13.44, taxIVA: 1.44, taxDebit: 0.30, taxCredit: 0.60, sellerCommission: 60, type: "S", retentionIVA: true, active: true, promo: { discountDay: 0, cash: 12 } },
  { code: "SERVUNA21", category: "UNIAS", description: "[%60] Retoque de acrílicas retoque cambio de diseño", baseValue: 15.00, finalValue: 16.80, taxIVA: 1.80, taxDebit: 0.38, taxCredit: 0.75, sellerCommission: 60, type: "S", retentionIVA: true, active: true, promo: { discountDay: 0, cash: 12 } },
  { code: "SERVUNA24", category: "UNIAS", description: "[%60] Retiro de acrílicas", baseValue: 8.00, finalValue: 8.96, taxIVA: 0.96, taxDebit: 0.20, taxCredit: 0.40, sellerCommission: 60, type: "S", retentionIVA: true, active: true, promo: { discountDay: 0, cash: 12 } },
  { code: "SERVUNA27", category: "UNIAS", description: "[%60] Pedicure spa hombre", baseValue: 6.00, finalValue: 6.72, taxIVA: 0.72, taxDebit: 0.15, taxCredit: 0.30, sellerCommission: 60, type: "S", retentionIVA: true, active: true, promo: { discountDay: 0, cash: 12 } },
  { code: "SERVUNA30", category: "UNIAS", description: "[%60] Pedicure spa + esmaltado tradicional", baseValue: 8.00, finalValue: 8.96, taxIVA: 0.96, taxDebit: 0.20, taxCredit: 0.40, sellerCommission: 60, type: "S", retentionIVA: true, active: true, promo: { discountDay: 0, cash: 12 } },
  { code: "SERVUNA33", category: "UNIAS", description: "[%60] Pedicure spa + esmaltado semipermanente", baseValue: 13.00, finalValue: 14.56, taxIVA: 1.56, taxDebit: 0.33, taxCredit: 0.65, sellerCommission: 60, type: "S", retentionIVA: true, active: true, promo: { discountDay: 0, cash: 12 } },
  { code: "SERVDPI01", category: "ESPECIALES", description: "[%60] Depilación de bigote mujer", baseValue: 5.00, finalValue: 5.60, taxIVA: 0.60, taxDebit: 0.13, taxCredit: 0.25, sellerCommission: 60, type: "S", retentionIVA: true, active: true, promo: { discountDay: 0, cash: 12 } }
]